spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/own_app
    username: postgres
    password: rewansh@12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port:
    1010